name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg CACHEBUST=$(date +%s) -t yogendra311/client:${IMAGE_TAG} ./letstalk
          docker build --build-arg CACHEBUST=$(date +%s) -t yogendra311/server:${IMAGE_TAG} ./backend
          docker push yogendra311/client:${IMAGE_TAG}
          docker push yogendra311/server:${IMAGE_TAG}

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            git pull origin master
            export IMAGE_TAG=${{ github.sha }}
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d --force-recreate
            sudo docker system prune -af
